name: Eva Nedeliakova, sad and tired student
markdown: kramdown
permalink: /blog/:year/:month/:day/:title

collections:
    hobbies:
        output: true
    projects:
        output: true
    layouts:
        output: true

plugins:
  - jemoji
