name: Eva Nedeliakova, sad and tired student
markdown: kramdown
permalink: /blog/:year/:month/:day/:title

collections:
    hobbies:
        output: true
    projects:
        output: true

defaults:
- scope:
path: ""
type: hobbies
values:
layout: hobby.html

plugins:
  - jemoji
